use std::path::{Path, PathBuf};

use anyhow::Result;
use serde::Serialize;

use crate::config::{is_modsync_installed, Config, ModSyncConfig};
use crate::db::Database;

/// A single syncPath entry in ModSync's config.jsonc.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SyncPathEntry {
    path: String,
    name: String,
    enabled: bool,
    enforced: bool,
    silent: bool,
    restart_required: bool,
}

/// The full ModSync config.jsonc structure.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct ModSyncOutputConfig {
    sync_paths: Vec<SyncPathEntry>,
    exclusions: Vec<String>,
}

pub fn modsync_config_path(spt_dir: &Path) -> PathBuf {
    spt_dir.join("user/mods/Corter-ModSync/config.jsonc")
}

/// Generate ModSync config from DB state + quartermaster config.
fn generate_config(ms_config: &ModSyncConfig, db: &Database) -> Result<ModSyncOutputConfig> {
    let mods = db.list_mods()?;
    let mut sync_paths: Vec<SyncPathEntry> = Vec::new();

    for m in &mods {
        let files = db.get_files_for_mod(m.id)?;
        let client_files: Vec<&str> = files
            .iter()
            .filter(|f| f.file_path.starts_with("BepInEx/"))
            .map(|f| f.file_path.as_str())
            .collect();

        if client_files.is_empty() {
            continue;
        }

        let forge_id_str = m.forge_mod_id.to_string();
        let overrides = ms_config.overrides.get(&forge_id_str);

        for dir in deduplicate_to_directories(&client_files) {
            sync_paths.push(SyncPathEntry {
                path: dir.clone(),
                name: m.name.clone(),
                enabled: overrides.and_then(|o| o.enabled).unwrap_or(true),
                enforced: overrides
                    .and_then(|o| o.enforced)
                    .unwrap_or(ms_config.enforced),
                silent: overrides.and_then(|o| o.silent).unwrap_or(ms_config.silent),
                restart_required: overrides
                    .and_then(|o| o.restart_required)
                    .unwrap_or(ms_config.restart_required),
            });
        }
    }

    for extra in &ms_config.extra_sync_paths {
        sync_paths.push(SyncPathEntry {
            path: extra.clone(),
            name: extra.clone(),
            enabled: true,
            enforced: ms_config.enforced,
            silent: ms_config.silent,
            restart_required: ms_config.restart_required,
        });
    }

    sync_paths.sort_by(|a, b| a.path.cmp(&b.path));

    Ok(ModSyncOutputConfig {
        sync_paths,
        exclusions: ms_config.exclusions.clone(),
    })
}

/// Given a list of file paths under BepInEx/, deduplicate to the minimal
/// set of directories. If multiple files share a common parent like
/// `BepInEx/plugins/SAIN/`, use the directory. If a file is alone at a
/// level (e.g., `BepInEx/patchers/Mod.dll`), use the file path directly.
fn deduplicate_to_directories(paths: &[&str]) -> Vec<String> {
    use std::collections::BTreeSet;
    let mut dirs: BTreeSet<String> = BTreeSet::new();

    for path in paths {
        let parts: Vec<&str> = path.split('/').collect();
        // BepInEx/<category>/<mod_name_or_file>/...
        // If 3+ parts and the 3rd part has no extension, treat first 3 as directory
        // If 3 parts and the last has an extension, it's a standalone file
        if parts.len() >= 3 {
            let third = parts[2];
            if parts.len() == 3 && third.contains('.') {
                // Standalone file like BepInEx/patchers/Mod.dll
                dirs.insert(path.to_string());
            } else {
                // Directory like BepInEx/plugins/SAIN
                dirs.insert(format!("{}/{}/{}", parts[0], parts[1], third));
            }
        }
    }

    dirs.into_iter().collect()
}

/// Write a ModSyncOutputConfig to config.jsonc atomically.
fn write_config(config_path: &Path, output: &ModSyncOutputConfig) -> Result<()> {
    let json = serde_json::to_string_pretty(output)?;
    let content =
        format!("// Generated by quartermaster — manual edits will be overwritten\n{json}\n");

    let tmp_path = config_path.with_extension("jsonc.tmp");
    std::fs::write(&tmp_path, &content)?;
    std::fs::rename(&tmp_path, config_path)?;

    tracing::debug!(path = %config_path.display(), "wrote ModSync config");
    Ok(())
}

/// Regenerate config.jsonc if ModSync is installed and [modsync] config is present.
/// Returns true if the config was written, false if skipped.
pub fn regenerate_if_enabled(spt_dir: &Path, config: &Config, db: &Database) -> Result<bool> {
    let ms_config = match &config.modsync {
        Some(c) => c,
        None => return Ok(false),
    };

    if !is_modsync_installed(spt_dir) {
        tracing::debug!("ModSync not installed, skipping config generation");
        return Ok(false);
    }

    let output = generate_config(ms_config, db)?;
    let config_path = modsync_config_path(spt_dir);
    write_config(&config_path, &output)?;

    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ModSyncConfig, ModSyncOverride};
    use crate::db::Database;

    fn setup_db_with_client_mod(db: &Database) -> i64 {
        let mod_id = db
            .insert_mod(100, 200, "SAIN", Some("sain"), "3.2.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/SAIN/SAIN.dll",
            Some("abc123"),
            Some(1024),
        )
        .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/SAIN/config.json",
            Some("def456"),
            Some(256),
        )
        .unwrap();
        mod_id
    }

    fn setup_db_with_server_mod(db: &Database) -> i64 {
        let mod_id = db
            .insert_mod(200, 300, "ServerMod", Some("server-mod"), "1.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "SPT/user/mods/ServerMod/package.json",
            Some("aaa111"),
            Some(512),
        )
        .unwrap();
        mod_id
    }

    fn setup_db_with_hybrid_mod(db: &Database) -> i64 {
        let mod_id = db
            .insert_mod(300, 400, "HybridMod", Some("hybrid-mod"), "2.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/HybridMod/hybrid.dll",
            Some("bbb222"),
            Some(2048),
        )
        .unwrap();
        db.insert_file(
            mod_id,
            "SPT/user/mods/HybridMod/package.json",
            Some("ccc333"),
            Some(128),
        )
        .unwrap();
        mod_id
    }

    #[test]
    fn generate_config_client_mod_creates_sync_path() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].path, "BepInEx/plugins/SAIN");
        assert_eq!(output.sync_paths[0].name, "SAIN");
        assert!(output.sync_paths[0].enforced); // global default
        assert!(!output.sync_paths[0].silent); // global default
        assert!(output.sync_paths[0].restart_required);
        assert!(output.sync_paths[0].enabled);
    }

    #[test]
    fn generate_config_server_only_mod_excluded() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_server_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert!(output.sync_paths.is_empty());
    }

    #[test]
    fn generate_config_hybrid_mod_only_syncs_client_paths() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_hybrid_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].path, "BepInEx/plugins/HybridMod");
        assert_eq!(output.sync_paths[0].name, "HybridMod");
    }

    #[test]
    fn generate_config_per_mod_override_applied() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db); // forge_mod_id = 100

        let mut ms_config = ModSyncConfig::default();
        ms_config.overrides.insert(
            "100".to_string(),
            ModSyncOverride {
                enforced: Some(false),
                silent: Some(true),
                restart_required: None,
                enabled: None,
            },
        );

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert!(!output.sync_paths[0].enforced); // overridden
        assert!(output.sync_paths[0].silent); // overridden
        assert!(output.sync_paths[0].restart_required); // global default (not overridden)
    }

    #[test]
    fn generate_config_disabled_mod_override() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db); // forge_mod_id = 100

        let mut ms_config = ModSyncConfig::default();
        ms_config.overrides.insert(
            "100".to_string(),
            ModSyncOverride {
                enabled: Some(false),
                enforced: None,
                silent: None,
                restart_required: None,
            },
        );

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert!(!output.sync_paths[0].enabled);
    }

    #[test]
    fn generate_config_extra_sync_paths_included() {
        let db = Database::open_in_memory().unwrap();

        let mut ms_config = ModSyncConfig::default();
        ms_config.extra_sync_paths = vec!["BepInEx/config".to_string()];

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].path, "BepInEx/config");
        assert_eq!(output.sync_paths[0].name, "BepInEx/config");
        assert!(output.sync_paths[0].enforced); // uses global defaults
    }

    #[test]
    fn generate_config_exclusions_passed_through() {
        let db = Database::open_in_memory().unwrap();

        let mut ms_config = ModSyncConfig::default();
        ms_config.exclusions = vec!["**/*.nosync".to_string(), "BepInEx/plugins/spt".to_string()];

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(
            output.exclusions,
            vec!["**/*.nosync", "BepInEx/plugins/spt"]
        );
    }

    #[test]
    fn generate_config_multiple_mods_sorted() {
        let db = Database::open_in_memory().unwrap();
        // Insert two client mods
        let mod1 = db
            .insert_mod(100, 200, "Zebra", Some("zebra"), "1.0.0")
            .unwrap();
        db.insert_file(mod1, "BepInEx/plugins/Zebra/z.dll", Some("aaa"), Some(100))
            .unwrap();

        let mod2 = db
            .insert_mod(101, 201, "Alpha", Some("alpha"), "1.0.0")
            .unwrap();
        db.insert_file(mod2, "BepInEx/plugins/Alpha/a.dll", Some("bbb"), Some(100))
            .unwrap();

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 2);
        // Should be sorted by path for deterministic output
        assert_eq!(output.sync_paths[0].path, "BepInEx/plugins/Alpha");
        assert_eq!(output.sync_paths[1].path, "BepInEx/plugins/Zebra");
    }

    #[test]
    fn generate_config_global_defaults_applied() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let ms_config = ModSyncConfig {
            enforced: false,
            silent: true,
            restart_required: false,
            ..ModSyncConfig::default()
        };
        let output = generate_config(&ms_config, &db).unwrap();

        assert!(!output.sync_paths[0].enforced);
        assert!(output.sync_paths[0].silent);
        assert!(!output.sync_paths[0].restart_required);
    }

    #[test]
    fn generate_config_mod_with_patcher_files() {
        let db = Database::open_in_memory().unwrap();
        let mod_id = db
            .insert_mod(500, 600, "PatcherMod", Some("patcher-mod"), "1.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/patchers/PatcherMod.dll",
            Some("ppp111"),
            Some(512),
        )
        .unwrap();

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        // Single file patcher — sync path is the file itself
        assert_eq!(output.sync_paths[0].path, "BepInEx/patchers/PatcherMod.dll");
    }

    #[test]
    fn write_config_creates_jsonc_with_header() {
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.jsonc");

        let output = ModSyncOutputConfig {
            sync_paths: vec![SyncPathEntry {
                path: "BepInEx/plugins/Test".to_string(),
                name: "Test".to_string(),
                enabled: true,
                enforced: true,
                silent: false,
                restart_required: true,
            }],
            exclusions: vec!["**/*.nosync".to_string()],
        };

        write_config(&config_path, &output).unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(content.starts_with("// Generated by quartermaster"));
        // Should be valid JSON after removing the comment line
        let json_part: String = content.lines().skip(1).collect::<Vec<_>>().join("\n");
        let parsed: serde_json::Value = serde_json::from_str(&json_part).unwrap();
        assert!(parsed["syncPaths"].is_array());
        assert_eq!(parsed["syncPaths"][0]["path"], "BepInEx/plugins/Test");
        assert_eq!(parsed["syncPaths"][0]["name"], "Test");
    }

    #[test]
    fn regenerate_if_enabled_skips_when_no_modsync_config() {
        let tmp = tempfile::tempdir().unwrap();
        let db = Database::open_in_memory().unwrap();
        let config = Config::default(); // modsync: None

        let result = regenerate_if_enabled(tmp.path(), &config, &db).unwrap();
        assert!(!result);
    }

    #[test]
    fn regenerate_if_enabled_skips_when_modsync_not_installed() {
        let tmp = tempfile::tempdir().unwrap();
        let db = Database::open_in_memory().unwrap();
        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig::default());
        // Don't create the Corter-ModSync directory

        let result = regenerate_if_enabled(tmp.path(), &config, &db).unwrap();
        assert!(!result);
    }

    #[test]
    fn regenerate_if_enabled_writes_when_configured_and_installed() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("user/mods/Corter-ModSync")).unwrap();

        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig::default());

        let result = regenerate_if_enabled(tmp.path(), &config, &db).unwrap();
        assert!(result);

        let config_path = modsync_config_path(tmp.path());
        assert!(config_path.exists());
    }

    #[test]
    fn full_lifecycle_install_update_remove() {
        let tmp = tempfile::tempdir().unwrap();
        let spt_dir = tmp.path();
        std::fs::create_dir_all(spt_dir.join("user/mods/Corter-ModSync")).unwrap();

        let db = Database::open_in_memory().unwrap();
        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig::default());

        // Install a client mod
        let mod_id = db
            .insert_mod(100, 200, "TestClientMod", Some("test-client"), "1.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/TestClientMod/test.dll",
            Some("hash1"),
            Some(1024),
        )
        .unwrap();

        let result = regenerate_if_enabled(spt_dir, &config, &db).unwrap();
        assert!(result);

        let content = std::fs::read_to_string(modsync_config_path(spt_dir)).unwrap();
        assert!(content.contains("TestClientMod"));
        assert!(content.contains("BepInEx/plugins/TestClientMod"));

        // Update — add a second file (simulating version update)
        db.insert_file(
            mod_id,
            "BepInEx/plugins/TestClientMod/extra.dll",
            Some("hash2"),
            Some(512),
        )
        .unwrap();

        let result = regenerate_if_enabled(spt_dir, &config, &db).unwrap();
        assert!(result);

        // Remove the mod
        db.delete_files_for_mod(mod_id).unwrap();
        db.delete_mod(mod_id).unwrap();

        let result = regenerate_if_enabled(spt_dir, &config, &db).unwrap();
        assert!(result);

        let content = std::fs::read_to_string(modsync_config_path(spt_dir)).unwrap();
        assert!(!content.contains("TestClientMod"));
    }

    #[test]
    fn full_lifecycle_mixed_mods() {
        let tmp = tempfile::tempdir().unwrap();
        let spt_dir = tmp.path();
        std::fs::create_dir_all(spt_dir.join("user/mods/Corter-ModSync")).unwrap();

        let db = Database::open_in_memory().unwrap();
        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig {
            extra_sync_paths: vec!["BepInEx/config".to_string()],
            exclusions: vec!["**/*.log".to_string()],
            ..ModSyncConfig::default()
        });

        // Server-only mod — should not appear in syncPaths
        let _server_mod = db
            .insert_mod(200, 300, "ServerOnly", None, "1.0.0")
            .unwrap();
        db.insert_file(
            _server_mod,
            "SPT/user/mods/ServerOnly/package.json",
            Some("s1"),
            Some(100),
        )
        .unwrap();

        // Client mod — should appear
        let client_mod = db.insert_mod(300, 400, "ClientMod", None, "1.0.0").unwrap();
        db.insert_file(
            client_mod,
            "BepInEx/plugins/ClientMod/client.dll",
            Some("c1"),
            Some(200),
        )
        .unwrap();

        regenerate_if_enabled(spt_dir, &config, &db).unwrap();

        let content = std::fs::read_to_string(modsync_config_path(spt_dir)).unwrap();
        let json_part: String = content.lines().skip(1).collect::<Vec<_>>().join("\n");
        let parsed: serde_json::Value = serde_json::from_str(&json_part).unwrap();

        let paths: Vec<&str> = parsed["syncPaths"]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| p["path"].as_str().unwrap())
            .collect();

        assert!(paths.contains(&"BepInEx/plugins/ClientMod"));
        assert!(paths.contains(&"BepInEx/config"));
        assert!(!paths.iter().any(|p| p.contains("ServerOnly")));

        let exclusions: Vec<&str> = parsed["exclusions"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| e.as_str().unwrap())
            .collect();
        assert_eq!(exclusions, vec!["**/*.log"]);
    }
}
