use std::path::{Path, PathBuf};

use anyhow::Result;
use serde::Serialize;

use crate::config::{find_narconet_dir, Config, ModSyncConfig, NARCONET_FORGE_MOD_ID};
use crate::db::Database;

/// A single syncPath entry in NarcoNet's config.yaml.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SyncPathEntry {
    path: String,
    name: String,
    enabled: bool,
    enforced: bool,
    silent: bool,
    restart_required: bool,
}

/// The full NarcoNet config.yaml structure.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct ModSyncOutputConfig {
    sync_paths: Vec<SyncPathEntry>,
    exclusions: Vec<String>,
}

pub fn modsync_config_path(spt_dir: &Path) -> Option<PathBuf> {
    find_narconet_dir(spt_dir).map(|dir| dir.join("config.yaml"))
}

fn prepend_parent_if_needed(path: &str) -> String {
    if path.starts_with("BepInEx/") || path == "BepInEx" {
        format!("../{path}")
    } else {
        path.to_string()
    }
}

/// Generate ModSync config from DB state + quartermaster config.
fn generate_config(ms_config: &ModSyncConfig, db: &Database) -> Result<ModSyncOutputConfig> {
    let mods = db.list_mods()?;
    let mut sync_paths: Vec<SyncPathEntry> = Vec::new();

    for m in &mods {
        if m.forge_mod_id == NARCONET_FORGE_MOD_ID {
            continue;
        }

        let files = db.get_files_for_mod(m.id)?;
        let client_files: Vec<&str> = files
            .iter()
            .filter(|f| f.file_path.starts_with("BepInEx/"))
            .map(|f| f.file_path.as_str())
            .collect();

        if client_files.is_empty() {
            continue;
        }

        let forge_id_str = m.forge_mod_id.to_string();
        let overrides = ms_config.overrides.get(&forge_id_str);

        for dir in deduplicate_to_directories(&client_files) {
            sync_paths.push(SyncPathEntry {
                path: prepend_parent_if_needed(&dir),
                name: m.name.clone(),
                enabled: overrides.and_then(|o| o.enabled).unwrap_or(true),
                enforced: overrides
                    .and_then(|o| o.enforced)
                    .unwrap_or(ms_config.enforced),
                silent: overrides.and_then(|o| o.silent).unwrap_or(ms_config.silent),
                restart_required: overrides
                    .and_then(|o| o.restart_required)
                    .unwrap_or(ms_config.restart_required),
            });
        }
    }

    for extra in &ms_config.extra_sync_paths {
        sync_paths.push(SyncPathEntry {
            path: prepend_parent_if_needed(extra),
            name: extra.clone(),
            enabled: true,
            enforced: ms_config.enforced,
            silent: ms_config.silent,
            restart_required: ms_config.restart_required,
        });
    }

    sync_paths.sort_by(|a, b| a.path.cmp(&b.path));

    let exclusions = ms_config
        .exclusions
        .iter()
        .map(|e| prepend_parent_if_needed(e))
        .collect();

    Ok(ModSyncOutputConfig {
        sync_paths,
        exclusions,
    })
}

/// Given a list of file paths under BepInEx/, deduplicate to the minimal
/// set of directories. If multiple files share a common parent like
/// `BepInEx/plugins/SAIN/`, use the directory. If a file is alone at a
/// level (e.g., `BepInEx/patchers/Mod.dll`), use the file path directly.
fn deduplicate_to_directories(paths: &[&str]) -> Vec<String> {
    use std::collections::BTreeSet;
    let mut dirs: BTreeSet<String> = BTreeSet::new();

    for path in paths {
        let parts: Vec<&str> = path.split('/').collect();
        // BepInEx/<category>/<mod_name_or_file>/...
        // If 3+ parts and the 3rd part has no extension, treat first 3 as directory
        // If 3 parts and the last has an extension, it's a standalone file
        if parts.len() >= 3 {
            let third = parts[2];
            if parts.len() == 3 && third.contains('.') {
                // Standalone file like BepInEx/patchers/Mod.dll
                dirs.insert(path.to_string());
            } else {
                // Directory like BepInEx/plugins/SAIN
                dirs.insert(format!("{}/{}/{}", parts[0], parts[1], third));
            }
        }
    }

    dirs.into_iter().collect()
}

/// Write a ModSyncOutputConfig to config.yaml atomically.
fn write_config(config_path: &Path, output: &ModSyncOutputConfig) -> Result<()> {
    use anyhow::Context;
    let yaml =
        serde_saphyr::to_string(output).context("failed to serialize modsync config to YAML")?;
    let content =
        format!("# Generated by quartermaster — manual edits will be overwritten\n{yaml}");

    let tmp_path = config_path.with_extension("yaml.tmp");
    std::fs::write(&tmp_path, &content)?;
    std::fs::rename(&tmp_path, config_path)?;

    tracing::debug!(path = %config_path.display(), "wrote NarcoNet config");
    Ok(())
}

/// Regenerate config.yaml if NarcoNet is installed and [modsync] config is present.
/// Returns true if the config was written, false if skipped.
pub fn regenerate_if_enabled(spt_dir: &Path, config: &Config, db: &Database) -> Result<bool> {
    let ms_config = match &config.modsync {
        Some(c) => c,
        None => return Ok(false),
    };

    let config_path = match modsync_config_path(spt_dir) {
        Some(p) => p,
        None => {
            tracing::debug!("NarcoNet not installed, skipping config generation");
            return Ok(false);
        }
    };

    let output = generate_config(ms_config, db)?;
    write_config(&config_path, &output)?;

    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ModSyncConfig, ModSyncOverride, NARCONET_FORGE_MOD_ID};
    use crate::db::Database;

    fn setup_db_with_client_mod(db: &Database) -> i64 {
        let mod_id = db
            .insert_mod(100, 200, "SAIN", Some("sain"), "3.2.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/SAIN/SAIN.dll",
            Some("abc123"),
            Some(1024),
        )
        .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/SAIN/config.json",
            Some("def456"),
            Some(256),
        )
        .unwrap();
        mod_id
    }

    fn setup_db_with_server_mod(db: &Database) -> i64 {
        let mod_id = db
            .insert_mod(200, 300, "ServerMod", Some("server-mod"), "1.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "SPT/user/mods/ServerMod/package.json",
            Some("aaa111"),
            Some(512),
        )
        .unwrap();
        mod_id
    }

    fn setup_db_with_hybrid_mod(db: &Database) -> i64 {
        let mod_id = db
            .insert_mod(300, 400, "HybridMod", Some("hybrid-mod"), "2.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/HybridMod/hybrid.dll",
            Some("bbb222"),
            Some(2048),
        )
        .unwrap();
        db.insert_file(
            mod_id,
            "SPT/user/mods/HybridMod/package.json",
            Some("ccc333"),
            Some(128),
        )
        .unwrap();
        mod_id
    }

    #[test]
    fn prepend_parent_handles_bare_bepinex() {
        assert_eq!(prepend_parent_if_needed("BepInEx"), "../BepInEx");
        assert_eq!(
            prepend_parent_if_needed("BepInEx/plugins"),
            "../BepInEx/plugins"
        );
        assert_eq!(prepend_parent_if_needed("user/mods"), "user/mods");
    }

    #[test]
    fn generate_config_client_mod_creates_sync_path() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].path, "../BepInEx/plugins/SAIN");
        assert_eq!(output.sync_paths[0].name, "SAIN");
        assert!(output.sync_paths[0].enforced);
        assert!(!output.sync_paths[0].silent);
        assert!(output.sync_paths[0].restart_required);
        assert!(output.sync_paths[0].enabled);
    }

    #[test]
    fn generate_config_server_only_mod_excluded() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_server_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert!(output.sync_paths.is_empty());
    }

    #[test]
    fn generate_config_hybrid_mod_only_syncs_client_paths() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_hybrid_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].path, "../BepInEx/plugins/HybridMod");
        assert_eq!(output.sync_paths[0].name, "HybridMod");
    }

    #[test]
    fn generate_config_per_mod_override_applied() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let mut ms_config = ModSyncConfig::default();
        ms_config.overrides.insert(
            "100".to_string(),
            ModSyncOverride {
                enforced: Some(false),
                silent: Some(true),
                restart_required: None,
                enabled: None,
            },
        );

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert!(!output.sync_paths[0].enforced);
        assert!(output.sync_paths[0].silent);
        assert!(output.sync_paths[0].restart_required);
    }

    #[test]
    fn generate_config_disabled_mod_override() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let mut ms_config = ModSyncConfig::default();
        ms_config.overrides.insert(
            "100".to_string(),
            ModSyncOverride {
                enabled: Some(false),
                enforced: None,
                silent: None,
                restart_required: None,
            },
        );

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert!(!output.sync_paths[0].enabled);
    }

    #[test]
    fn generate_config_extra_sync_paths_get_prefix() {
        let db = Database::open_in_memory().unwrap();

        let mut ms_config = ModSyncConfig::default();
        ms_config.extra_sync_paths = vec!["BepInEx/config".to_string()];

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].path, "../BepInEx/config");
        assert_eq!(output.sync_paths[0].name, "BepInEx/config");
        assert!(output.sync_paths[0].enforced);
    }

    #[test]
    fn generate_config_exclusions_get_prefix() {
        let db = Database::open_in_memory().unwrap();

        let mut ms_config = ModSyncConfig::default();
        ms_config.exclusions = vec!["**/*.nosync".to_string(), "BepInEx/plugins/spt".to_string()];

        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(
            output.exclusions,
            vec!["**/*.nosync", "../BepInEx/plugins/spt"]
        );
    }

    #[test]
    fn generate_config_multiple_mods_sorted() {
        let db = Database::open_in_memory().unwrap();
        let mod1 = db
            .insert_mod(100, 200, "Zebra", Some("zebra"), "1.0.0")
            .unwrap();
        db.insert_file(mod1, "BepInEx/plugins/Zebra/z.dll", Some("aaa"), Some(100))
            .unwrap();

        let mod2 = db
            .insert_mod(101, 201, "Alpha", Some("alpha"), "1.0.0")
            .unwrap();
        db.insert_file(mod2, "BepInEx/plugins/Alpha/a.dll", Some("bbb"), Some(100))
            .unwrap();

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 2);
        assert_eq!(output.sync_paths[0].path, "../BepInEx/plugins/Alpha");
        assert_eq!(output.sync_paths[1].path, "../BepInEx/plugins/Zebra");
    }

    #[test]
    fn generate_config_global_defaults_applied() {
        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let ms_config = ModSyncConfig {
            enforced: false,
            silent: true,
            restart_required: false,
            ..ModSyncConfig::default()
        };
        let output = generate_config(&ms_config, &db).unwrap();

        assert!(!output.sync_paths[0].enforced);
        assert!(output.sync_paths[0].silent);
        assert!(!output.sync_paths[0].restart_required);
    }

    #[test]
    fn generate_config_mod_with_patcher_files() {
        let db = Database::open_in_memory().unwrap();
        let mod_id = db
            .insert_mod(500, 600, "PatcherMod", Some("patcher-mod"), "1.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/patchers/PatcherMod.dll",
            Some("ppp111"),
            Some(512),
        )
        .unwrap();

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(
            output.sync_paths[0].path,
            "../BepInEx/patchers/PatcherMod.dll"
        );
    }

    #[test]
    fn generate_config_narconet_self_excluded() {
        let db = Database::open_in_memory().unwrap();
        // NarcoNet's own mod with Forge ID 2441
        let mod_id = db
            .insert_mod(
                NARCONET_FORGE_MOD_ID,
                999,
                "NarcoNet",
                Some("narconet"),
                "1.0.16",
            )
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/MadManBeavis-NarcoNet/NarcoNet.dll",
            Some("nnn111"),
            Some(4096),
        )
        .unwrap();

        // A normal client mod should still appear
        setup_db_with_client_mod(&db);

        let ms_config = ModSyncConfig::default();
        let output = generate_config(&ms_config, &db).unwrap();

        // Only SAIN should appear, not NarcoNet
        assert_eq!(output.sync_paths.len(), 1);
        assert_eq!(output.sync_paths[0].name, "SAIN");
    }

    #[test]
    fn write_config_creates_yaml_with_header() {
        let tmp = tempfile::tempdir().unwrap();
        let config_path = tmp.path().join("config.yaml");

        let output = ModSyncOutputConfig {
            sync_paths: vec![SyncPathEntry {
                path: "../BepInEx/plugins/Test".to_string(),
                name: "Test".to_string(),
                enabled: true,
                enforced: true,
                silent: false,
                restart_required: true,
            }],
            exclusions: vec!["**/*.nosync".to_string()],
        };

        write_config(&config_path, &output).unwrap();

        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(content.starts_with("# Generated by quartermaster"));
        // Should be valid YAML
        let parsed: serde_json::Value = serde_saphyr::from_str(&content).unwrap();
        assert!(parsed["syncPaths"].is_array());

        // Verify field values
        let sync_path = &parsed["syncPaths"][0];
        assert_eq!(
            sync_path["path"].as_str().unwrap(),
            "../BepInEx/plugins/Test"
        );
        assert_eq!(sync_path["name"].as_str().unwrap(), "Test");
        assert_eq!(sync_path["enabled"].as_bool().unwrap(), true);
    }

    #[test]
    fn regenerate_if_enabled_skips_when_no_modsync_config() {
        let tmp = tempfile::tempdir().unwrap();
        let db = Database::open_in_memory().unwrap();
        let config = Config::default();

        let result = regenerate_if_enabled(tmp.path(), &config, &db).unwrap();
        assert!(!result);
    }

    #[test]
    fn regenerate_if_enabled_skips_when_narconet_not_installed() {
        let tmp = tempfile::tempdir().unwrap();
        let db = Database::open_in_memory().unwrap();
        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig::default());

        let result = regenerate_if_enabled(tmp.path(), &config, &db).unwrap();
        assert!(!result);
    }

    #[test]
    fn regenerate_if_enabled_writes_when_configured_and_installed() {
        let tmp = tempfile::tempdir().unwrap();
        let narconet_dir = tmp.path().join("SPT/user/mods/narconet-server");
        std::fs::create_dir_all(&narconet_dir).unwrap();
        std::fs::write(narconet_dir.join("package.json"), "{}").unwrap();

        let db = Database::open_in_memory().unwrap();
        setup_db_with_client_mod(&db);

        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig::default());

        let result = regenerate_if_enabled(tmp.path(), &config, &db).unwrap();
        assert!(result);

        let config_path = modsync_config_path(tmp.path()).unwrap();
        assert!(config_path.exists());
        assert!(config_path.to_str().unwrap().ends_with("config.yaml"));
    }

    #[test]
    fn full_lifecycle_install_update_remove() {
        let tmp = tempfile::tempdir().unwrap();
        let spt_dir = tmp.path();
        let narconet_dir = spt_dir.join("SPT/user/mods/narconet-server");
        std::fs::create_dir_all(&narconet_dir).unwrap();
        std::fs::write(narconet_dir.join("package.json"), "{}").unwrap();

        let db = Database::open_in_memory().unwrap();
        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig::default());

        // Install a client mod
        let mod_id = db
            .insert_mod(100, 200, "TestClientMod", Some("test-client"), "1.0.0")
            .unwrap();
        db.insert_file(
            mod_id,
            "BepInEx/plugins/TestClientMod/test.dll",
            Some("hash1"),
            Some(1024),
        )
        .unwrap();

        let result = regenerate_if_enabled(spt_dir, &config, &db).unwrap();
        assert!(result);

        let content = std::fs::read_to_string(modsync_config_path(spt_dir).unwrap()).unwrap();
        assert!(content.contains("TestClientMod"));
        assert!(content.contains("../BepInEx/plugins/TestClientMod"));

        // Update — add a second file
        db.insert_file(
            mod_id,
            "BepInEx/plugins/TestClientMod/extra.dll",
            Some("hash2"),
            Some(512),
        )
        .unwrap();

        let result = regenerate_if_enabled(spt_dir, &config, &db).unwrap();
        assert!(result);

        // Remove the mod
        db.delete_files_for_mod(mod_id).unwrap();
        db.delete_mod(mod_id).unwrap();

        let result = regenerate_if_enabled(spt_dir, &config, &db).unwrap();
        assert!(result);

        let content = std::fs::read_to_string(modsync_config_path(spt_dir).unwrap()).unwrap();
        assert!(!content.contains("TestClientMod"));
    }

    #[test]
    fn full_lifecycle_mixed_mods() {
        let tmp = tempfile::tempdir().unwrap();
        let spt_dir = tmp.path();
        let narconet_dir = spt_dir.join("SPT/user/mods/narconet-server");
        std::fs::create_dir_all(&narconet_dir).unwrap();
        std::fs::write(narconet_dir.join("package.json"), "{}").unwrap();

        let db = Database::open_in_memory().unwrap();
        let mut config = Config::default();
        config.modsync = Some(ModSyncConfig {
            extra_sync_paths: vec!["BepInEx/config".to_string()],
            exclusions: vec!["**/*.log".to_string()],
            ..ModSyncConfig::default()
        });

        // Server-only mod
        let _server_mod = db
            .insert_mod(200, 300, "ServerOnly", None, "1.0.0")
            .unwrap();
        db.insert_file(
            _server_mod,
            "SPT/user/mods/ServerOnly/package.json",
            Some("s1"),
            Some(100),
        )
        .unwrap();

        // Client mod
        let client_mod = db.insert_mod(300, 400, "ClientMod", None, "1.0.0").unwrap();
        db.insert_file(
            client_mod,
            "BepInEx/plugins/ClientMod/client.dll",
            Some("c1"),
            Some(200),
        )
        .unwrap();

        regenerate_if_enabled(spt_dir, &config, &db).unwrap();

        let content = std::fs::read_to_string(modsync_config_path(spt_dir).unwrap()).unwrap();
        let parsed: serde_json::Value = serde_saphyr::from_str(&content).unwrap();

        let paths: Vec<String> = parsed["syncPaths"]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| p["path"].as_str().unwrap().to_string())
            .collect();

        assert!(paths.contains(&"../BepInEx/plugins/ClientMod".to_string()));
        assert!(paths.contains(&"../BepInEx/config".to_string()));
        assert!(!paths.iter().any(|p| p.contains("ServerOnly")));

        let exclusions: Vec<String> = parsed["exclusions"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| e.as_str().unwrap().to_string())
            .collect();
        assert_eq!(exclusions, vec!["**/*.log"]);
    }
}
